/**
 * Seed classes (M3c). Separated so we cannot tune a harness against the same
 * companies we later use to judge it — otherwise every improvement is
 * overfitting to our own benchmark and we would never know.
 *
 * The discipline is enforced in CODE, not documentation: a HOLDOUT seed
 * throws unless the caller explicitly declares it is the final evaluation.
 * (Same principle as the data-readiness gate — a prose rule is not a control.)
 */

export type SeedClass = "dev" | "validation" | "holdout";

export const SEED_RANGES: Record<SeedClass, { min: number; max: number }> = {
  dev: { min: 1000, max: 1099 },
  validation: { min: 2000, max: 2049 },
  holdout: { min: 9000, max: 9049 },
};

export class HoldoutSeedMisuse extends Error {}

export function seedClassOf(seed: number): SeedClass {
  for (const [name, range] of Object.entries(SEED_RANGES) as [
    SeedClass,
    { min: number; max: number },
  ][]) {
    if (seed >= range.min && seed <= range.max) return name;
  }
  throw new Error(
    `seed ${seed} belongs to no declared class. Use dev ${SEED_RANGES.dev.min}-${SEED_RANGES.dev.max}, ` +
      `validation ${SEED_RANGES.validation.min}-${SEED_RANGES.validation.max}, ` +
      `or holdout ${SEED_RANGES.holdout.min}-${SEED_RANGES.holdout.max}`
  );
}

export function seedsOf(cls: SeedClass, count: number): number[] {
  const { min, max } = SEED_RANGES[cls];
  const available = max - min + 1;
  if (count > available) throw new Error(`${cls} has only ${available} seeds, asked for ${count}`);
  return Array.from({ length: count }, (_, i) => min + i);
}

/**
 * Guards every generator entry point. `purpose: "final-evaluation"` is the
 * only way to touch holdout seeds, and it should appear in exactly one place
 * in the codebase — the final evaluation runner.
 */
export function assertSeedUsageAllowed(
  seed: number,
  purpose: "development" | "tuning" | "final-evaluation"
): void {
  const cls = seedClassOf(seed);
  if (cls === "holdout" && purpose !== "final-evaluation") {
    throw new HoldoutSeedMisuse(
      `seed ${seed} is a HOLDOUT seed and was requested for "${purpose}". ` +
        `Holdout companies may only be generated by the final evaluation runner — ` +
        `looking at them while building a harness is how we overfit our own benchmark.`
    );
  }
  if (cls === "dev" && purpose === "final-evaluation") {
    throw new HoldoutSeedMisuse(
      `seed ${seed} is a DEV seed and cannot be used for final evaluation — ` +
        `the harness was built while looking at it, so its score is not evidence.`
    );
  }
}
